export type Lang = "es" | "en";

export const ERP_NAME = "Kanri";

export const content = {
  es: {
    nav: {
      products: "Productos",
      case: "Caso real",
      about: "Nosotros",
      cta: "Agendar diagnóstico",
    },
    hero: {
      badge: "Estudio de software · Ciudad Juárez, México",
      title: "Construimos el software que la",
      titleAccent: "manufactura del norte de México",
      titleEnd: "necesita.",
      sub: "Ronin Studio es un estudio de producto que crea software de ingeniería industrial e IA para la maquila y sus proveedores. Hecho por ingenieros que vivieron el piso, no por programadores que nunca pisaron una planta.",
      ctaPrimary: "Ver productos",
      ctaSecondary: "Agendar diagnóstico",
      stat1: "+10 años",
      stat1Label: "en manufactura pesada (BRP / Can-Am)",
      stat2: "2 productos",
      stat2Label: "en producción: GENBA y Kanri",
      stat3: "IA aplicada",
      stat3Label: "donde aporta juicio, no donde está de moda",
    },
    pillars: {
      title: "Por qué Ronin Studio es distinto",
      items: [
        { t: "Venimos del piso", d: "Una década liderando proyectos e ingeniería en manufactura pesada. Hablamos Yamazumi, SPC, PFMEA y OEE como lengua materna." },
        { t: "IA aplicada, no de moda", d: "Los cálculos críticos viven en código; la IA aporta juicio y redacción. Controlamos costos y resultados — el ingeniero siempre en el bucle." },
        { t: "Software que se siente tuyo", d: "En español, white-label y a la medida del norte de México. Tu equipo ve tu marca, no la nuestra." },
      ],
    },
    products: {
      kicker: "Productos",
      title: "Dos productos. El mismo piso.",
      sub: "Software de planta listo para usarse, multi-tenant, que aplicamos a tu operación con pocas modificaciones.",
      genba: {
        tag: "Producto principal",
        name: "GENBA",
        tagline: "Estudios de tiempo, balanceo de línea (Yamazumi) y capacidad — desde un video, en minutos.",
        forWho: "Para el ingeniero industrial de la maquila.",
        steps: [
          { n: "01", t: "Captura", d: "Sube un video de la estación o captura las operaciones a mano. Desde tu teléfono, sin hardware." },
          { n: "02", t: "Analiza con IA", d: "Tiempos de ciclo, Yamazumi, cuello de botella, capacidad y OEE." },
          { n: "03", t: "Entregable firmable", d: "Estudio y reportes en PDF/Excel listos para firmar. Tú apruebas." },
        ],
        price: "Desde 450 USD/mes · demo de 20 días sin tarjeta",
        cta: "Probar GENBA gratis",
      },
      kanri: {
        tag: "Producto secundario",
        name: "Kanri",
        tagline: "ERP/CRM para talleres CNC y maquilas: del cotizar al embarque, bajo un solo techo digital.",
        flow: "Cotización → Compra → Diseño → Master Plan → Producción → Calidad ISO 9001 → Embarque → Portal del cliente",
        bullets: [
          "Reporte dimensional ISO 9001 con plano globalizado",
          "Master Plan PMI con escalamiento por volumen",
          "Portal del cliente con magic link · white-label",
        ],
        cta: "Conocer Kanri",
      },
    },
    caseStudy: {
      kicker: "Caso real",
      title: "Kanri en producción: IMC Design",
      sub: "Para IMC Design (manufactura CNC para maquiladoras en Juárez) digitalizamos la operación completa. Hoy lo ofrecemos como SaaS a otros talleres.",
      points: [
        { t: "Reporte dimensional ISO 9001", d: "Plano globalizado (ballooned) con OK/NG automático — nativo, no un extra." },
        { t: "Master Plan PMI realista", d: "Scheduler con días hábiles y escalamiento por volumen, no un Gantt manual." },
        { t: "Portal del cliente con magic link", d: "El cliente ve avance y entregables sin pelear con otro login." },
        { t: "White-label completo", d: "Cada taller ve su marca, no la nuestra. Listo para multi-tenant." },
      ],
      quote: "“Pasó de ser un sistema interno a un producto que vendemos como SaaS a otros talleres y maquilas.”",
    },
    founder: {
      kicker: "Quién está detrás",
      title: "Julio Ibarra — Julio Ronin",
      role: "Ingeniero en Sistemas Automotrices · Project Manager",
      body: "Una década liderando proyectos e ingeniería en manufactura pesada —BRP (Can-Am, Ski-Doo, Ryker), NPI/NPD de P1 a SOP— y ahora construyendo software con IA. Esa es la diferencia: no es software hecho por programadores que nunca pisaron una planta. Es software hecho por alguien que vivió el piso y el cronómetro.",
      tags: ["Lean & ergonomía", "Estudios de tiempo", "Project Management", "Forecast & business case", "Desarrollo con IA"],
    },
    finalCta: {
      title: "Pongamos tu operación en el mapa digital.",
      sub: "Prueba GENBA 20 días gratis, o agenda un diagnóstico de tu operación con Ronin Studio.",
      ctaPrimary: "Probar GENBA gratis",
      ctaSecondary: "Agendar diagnóstico",
      contact: "Ciudad Juárez, Chihuahua · ibarra.julio800@gmail.com",
    },
    footer: {
      tagline: "Software de ingeniería industrial e IA para la manufactura del norte de México.",
      products: "Productos",
      company: "Estudio",
      rights: "Todos los derechos reservados.",
    },
  },

  en: {
    nav: {
      products: "Products",
      case: "Real case",
      about: "About",
      cta: "Book a diagnostic",
    },
    hero: {
      badge: "Product studio · Ciudad Juárez, Mexico",
      title: "We build the software that",
      titleAccent: "Northern Mexico manufacturing",
      titleEnd: "needs.",
      sub: "Ronin Studio is a product studio building industrial-engineering software and AI for the maquila and its suppliers. Built by engineers who lived the floor — not coders who never set foot in a plant.",
      ctaPrimary: "See products",
      ctaSecondary: "Book a diagnostic",
      stat1: "+10 years",
      stat1Label: "in heavy manufacturing (BRP / Can-Am)",
      stat2: "2 products",
      stat2Label: "in production: GENBA and Kanri",
      stat3: "Applied AI",
      stat3Label: "where it adds judgment, not where it's trendy",
    },
    pillars: {
      title: "Why Ronin Studio is different",
      items: [
        { t: "We come from the floor", d: "A decade leading projects and engineering in heavy manufacturing. We speak Yamazumi, SPC, PFMEA and OEE as a native language." },
        { t: "Applied AI, not hype", d: "Critical math lives in code; AI brings judgment and writing. We control cost and results — the engineer is always in the loop." },
        { t: "Software that feels yours", d: "In Spanish, white-label and tailored to Northern Mexico. Your team sees your brand, not ours." },
      ],
    },
    products: {
      kicker: "Products",
      title: "Two products. The same floor.",
      sub: "Ready-to-use, multi-tenant shop-floor software we apply to your operation with few modifications.",
      genba: {
        tag: "Flagship product",
        name: "GENBA",
        tagline: "Time studies, line balancing (Yamazumi) and capacity — from a video, in minutes.",
        forWho: "For the industrial engineer of the maquila.",
        steps: [
          { n: "01", t: "Capture", d: "Upload a workstation video or log operations by hand. From your phone, no hardware." },
          { n: "02", t: "Analyze with AI", d: "Cycle times, Yamazumi, bottleneck, capacity and OEE." },
          { n: "03", t: "Signature-ready", d: "Study and reports as PDF/Excel ready to sign. You approve." },
        ],
        price: "From 450 USD/mo · 20-day trial, no card",
        cta: "Try GENBA free",
      },
      kanri: {
        tag: "Secondary product",
        name: "Kanri",
        tagline: "ERP/CRM for CNC shops and maquilas: from quote to shipping, under one digital roof.",
        flow: "Quote → Purchasing → Design → Master Plan → Production → ISO 9001 Quality → Shipping → Customer Portal",
        bullets: [
          "ISO 9001 dimensional report with ballooned drawing",
          "PMI Master Plan with volume scaling",
          "Customer portal via magic link · white-label",
        ],
        cta: "Explore Kanri",
      },
    },
    caseStudy: {
      kicker: "Real case",
      title: "Kanri in production: IMC Design",
      sub: "For IMC Design (CNC manufacturing for maquiladoras in Juárez) we digitized the entire operation. Today we offer it as SaaS to other shops.",
      points: [
        { t: "ISO 9001 dimensional report", d: "Ballooned drawing with automatic OK/NG — native, not an add-on." },
        { t: "Realistic PMI Master Plan", d: "Scheduler with business days and volume scaling, not a manual Gantt." },
        { t: "Customer portal via magic link", d: "Clients see progress and deliverables without fighting another login." },
        { t: "Full white-label", d: "Each shop sees its own brand, not ours. Multi-tenant ready." },
      ],
      quote: "“It went from an internal system to a product we sell as SaaS to other shops and maquilas.”",
    },
    founder: {
      kicker: "Who's behind it",
      title: "Julio Ibarra — Julio Ronin",
      role: "Automotive Systems Engineer · Project Manager",
      body: "A decade leading projects and engineering in heavy manufacturing —BRP (Can-Am, Ski-Doo, Ryker), NPI/NPD from P1 to SOP— now building software with AI. That's the difference: this isn't software made by coders who never set foot in a plant. It's software built by someone who lived the floor and the stopwatch.",
      tags: ["Lean & ergonomics", "Time studies", "Project Management", "Forecast & business case", "AI development"],
    },
    finalCta: {
      title: "Let's put your operation on the digital map.",
      sub: "Try GENBA free for 20 days, or book a diagnostic of your operation with Ronin Studio.",
      ctaPrimary: "Try GENBA free",
      ctaSecondary: "Book a diagnostic",
      contact: "Ciudad Juárez, Chihuahua · ibarra.julio800@gmail.com",
    },
    footer: {
      tagline: "Industrial-engineering software & AI for manufacturing in Northern Mexico.",
      products: "Products",
      company: "Studio",
      rights: "All rights reserved.",
    },
  },
};
